package alauncher.cn.measuringtablet.database.greenDao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import alauncher.cn.measuringtablet.bean.StepBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STEP_BEAN".
*/
public class StepBeanDao extends AbstractDao<StepBean, Long> {

    public static final String TABLENAME = "STEP_BEAN";

    /**
     * Properties of entity StepBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CodeID = new Property(1, long.class, "codeID", false, "CODE_ID");
        public final static Property StepID = new Property(2, int.class, "stepID", false, "STEP_ID");
        public final static Property Measured = new Property(3, int.class, "measured", false, "MEASURED");
    }


    public StepBeanDao(DaoConfig config) {
        super(config);
    }
    
    public StepBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STEP_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CODE_ID\" INTEGER NOT NULL ," + // 1: codeID
                "\"STEP_ID\" INTEGER NOT NULL ," + // 2: stepID
                "\"MEASURED\" INTEGER NOT NULL );"); // 3: measured
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_STEP_BEAN_CODE_ID_DESC_STEP_ID_DESC ON \"STEP_BEAN\"" +
                " (\"CODE_ID\" DESC,\"STEP_ID\" DESC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STEP_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, StepBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCodeID());
        stmt.bindLong(3, entity.getStepID());
        stmt.bindLong(4, entity.getMeasured());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, StepBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCodeID());
        stmt.bindLong(3, entity.getStepID());
        stmt.bindLong(4, entity.getMeasured());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public StepBean readEntity(Cursor cursor, int offset) {
        StepBean entity = new StepBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // codeID
            cursor.getInt(offset + 2), // stepID
            cursor.getInt(offset + 3) // measured
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, StepBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCodeID(cursor.getLong(offset + 1));
        entity.setStepID(cursor.getInt(offset + 2));
        entity.setMeasured(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(StepBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(StepBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(StepBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
